# /// script
# requires-python = ">=3.11"
# ///
"""
Bake the parsed suit-combination corpus (suitcomb.json) into combo/suit_encyclopedia.odin: a []Enc_Entry
of {n, s, line, targets}. The lookup KEY is NOT stored here — it is derived by the Odin engine at runtime
(`enc_key` serialises `sd_best_joint_table`), so equivalence is the engine's, not a hand-written rule. We
still de-duplicate exact holdings here (by the strict ownership pattern), keeping the richest/best line, so
alternative-line rows for one holding collapse to its best line.
"""
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(os.path.dirname(HERE), "suit_encyclopedia.odin")

OR_RE = re.compile(r",?\s+or\s+", re.I)
DANGLING_OR_RE = re.compile(r",?\s+or;?\s*$", re.I)  # an alternative that wrapped onto the next target's row


def clean_line(s):
    """Drop a trailing dangling connective ('A, or B, or' with the last alt spilled onto the next row)."""
    return DANGLING_OR_RE.sub("", s).strip()


def short_label(s):
    """Cell-label form of a line: the FIRST alternative of an 'A, or B, or C' menu (the primary play). The
    dropped alternatives and every per-target line remain in the tooltip, so nothing is lost — just shortened."""
    return clean_line(OR_RE.split(s)[0].strip())


def rle_key(n, s):
    """Strict ownership pattern — used ONLY to de-dupe exact-same holdings at bake time (never false-merges)."""
    syms = []
    for r in range(12, -1, -1):
        bit = 1 << r
        syms.append("N" if n & bit else "S" if s & bit else "o")
    rle, i = [], 0
    while i < len(syms):
        j = i
        while j < len(syms) and syms[j] == syms[i]:
            j += 1
        rle.append(f"{syms[i]}{j - i}")
        i = j
    return "".join(rle)


def usable_targets(row):
    """Per-target (need, pct, line) triples with a valid percentage and sane need; lines de-dangled."""
    return [(t["need"], t["pct"], clean_line(t["line"])) for t in row["targets"]
            if t["pct"] is not None and 0 <= t["need"] <= 13]


def score(row):
    """Rank rows sharing a holding: prefer more targets, then higher summed percentage."""
    ts = usable_targets(row)
    return (len(ts), sum(p for _, p, _ in ts))


def esc(s):
    return s.replace("\\", "\\\\").replace('"', '\\"')


def main():
    rows = json.load(open(f"{HERE}/suitcomb.json", encoding="utf-8"))
    best = {}
    for r in rows:
        ts = usable_targets(r)
        if not ts:
            continue
        r["_ts"] = ts
        k = rle_key(r["n_bits"], r["s_bits"])
        if k not in best or score(r) > score(best[k]):
            best[k] = r

    entries = list(best.values())
    lines = []
    for r in entries:
        ts = r["_ts"][:6]
        padded = ts + [(0, 0, "")] * (6 - len(ts))
        tlit = ", ".join(f'{{{nd},{p},"{esc(ln)[:70]}"}}' for nd, p, ln in padded)
        lines.append(
            f'\t{{0x{r["n_bits"]:04x}, 0x{r["s_bits"]:04x}, "{esc(short_label(r["remarks"]))[:70]}", '
            f'{len(ts)}, {{{tlit}}}}},'
        )
    body = "\n".join(lines)

    src = f'''package combo

// GENERATED by encyclopedia/bake_encyclopedia.py from the BridgeHands suit-combination tables.
// Do not edit by hand. Regenerate: uv run combo/encyclopedia/bake_encyclopedia.py
//
// A lookup table of single-suit holdings -> the published best line + its P(>=k) targets. Entries store the
// raw holding (n, s), a representative line label, the book's percentages, and a per-target line. The lookup
// KEY is derived from the ENGINE, not stored: `enc_key` serialises `sd_best_joint_table` (the recommended
// line's east_len x tricks joint counts), so two holdings share a key iff our single-dummy engine treats them
// identically. Engine equivalence collapses low-spot variants (good) BUT also merges ODDS-equivalent holdings
// with DIFFERENT honours (e.g. AQ9x/T8x missing KJ and AKJ9/xxx missing QT are both a double finesse -> same
// odds, same key). Their percentages are interchangeable, but the LINE TEXT names specific cards and does NOT
// transfer ("low to K" on a holding with no king). So a key hit is only ACCEPTED when the entry is also
// card-compatible with the live holding (same honours held by each side + same lengths, `honour_compatible`);
// otherwise it is a MISS and the caller falls back to the engine. A key can map to SEVERAL entries (the
// odds-equivalent-but-different-honour ones); the map stores every candidate and the lookup returns the first
// card-compatible one. Percentages are the book's (best defence).

import "core:strings"
import "core:sync"

Enc_Target :: struct {{
\tneed, pct: int,
\tline:      string, // the book's play to reach this trick target (card names valid for THIS holding)
}}
Enc_Entry :: struct {{
\tn, s:    u16,
\tline:    string, // representative label: the most-repeated per-target line (see modal_line in the parser)
\tnt:      int,
\ttargets: [6]Enc_Target,
}}

// Honours whose identity the line text depends on (Ten..Ace). Two holdings can share odds yet name different
// cards; requiring the same honours per side + same lengths guarantees the stored line text is literally valid.
@(private)
ENC_HONOURS :: u16(0x1F00)

// True when `entry` describes the SAME suit combination as the live (n, s) up to interchangeable low spots:
// each side holds the same honours (Ten+) and the same number of cards, in either hand assignment (the key is
// orientation-symmetric, so the entry may be stored mirrored). Guarantees the entry's card-named line applies.
@(private)
honour_compatible :: proc(n, s, en, es: u16) -> bool {{
\tdirect := n & ENC_HONOURS == en & ENC_HONOURS && s & ENC_HONOURS == es & ENC_HONOURS &&
\t\tcard_count(n) == card_count(en) && card_count(s) == card_count(es)
\tswap := n & ENC_HONOURS == es & ENC_HONOURS && s & ENC_HONOURS == en & ENC_HONOURS &&
\t\tcard_count(n) == card_count(es) && card_count(s) == card_count(en)
\treturn direct || swap
}}

// The engine equivalence key: the recommended line's joint (east_len x tricks) count table, serialised.
// Deterministic and identical whether called on a book entry or a live holding, so equal-behaviour holdings
// map together. Allocated in `allocator` (temp for lookups; the persistent heap when interned as a map key).
@(private)
enc_key :: proc(n, s: u16, allocator := context.temp_allocator) -> string {{
\tb := strings.builder_make(allocator)
\tstrings.write_int(&b, card_count(n | s))
\tstrings.write_byte(&b, ':')
\ttbl := sd_best_joint_table(n, s)
\tfor a in 0 ..= tbl.m {{
\t\tfor k in 0 ..= RANKS {{
\t\t\tc := tbl.count[a][k]
\t\t\tif c > 0.5 {{
\t\t\t\tstrings.write_int(&b, a)
\t\t\t\tstrings.write_byte(&b, '-')
\t\t\t\tstrings.write_int(&b, k)
\t\t\t\tstrings.write_byte(&b, '=')
\t\t\t\tstrings.write_int(&b, int(c + 0.5))
\t\t\t\tstrings.write_byte(&b, ',')
\t\t\t}}
\t\t}}
\t}}
\treturn strings.to_string(b)
}}

// key -> every entry index sharing that engine key. Usually one; several when odds-equivalent holdings with
// different honours collide (the lookup then card-filters). Slices live process-lifetime (freed at exit).
@(private)
g_enc_map: map[string][dynamic]int
@(private)
g_enc_once: sync.Once

@(private)
enc_build :: proc() {{
\tg_enc_map = make(map[string][dynamic]int)
\tfor e, i in enc_entries {{
\t\tk := enc_key(e.n, e.s, context.allocator) // interned; process-lifetime
\t\tif cur, exists := &g_enc_map[k]; exists {{
\t\t\tappend(cur, i)
\t\t\tdelete(k) // key already interned; drop the duplicate
\t\t}} else {{
\t\t\tg_enc_map[k] = make([dynamic]int)
\t\t\tappend(&g_enc_map[k], i)
\t\t}}
\t}}
}}

// Look up the published line + odds for an NS single-suit holding. Returns the entry and true on a hit;
// {{}},false on a miss (caller falls back to the engine). A key hit is only accepted when the entry is also
// card-compatible (`honour_compatible`) with the live holding, so an odds-equivalent entry that names cards
// this holding does not hold is rejected as a miss. The key map is built once, lazily, thread-safely.
encyclopedia_lookup :: proc(n, s: u16) -> (Enc_Entry, bool) {{
\tsync.once_do(&g_enc_once, enc_build)
\tk := enc_key(n, s, context.temp_allocator)
\tif cands, ok := g_enc_map[k]; ok {{
\t\tfor i in cands {{
\t\t\te := enc_entries[i]
\t\t\tif honour_compatible(n, s, e.n, e.s) {{return e, true}}
\t\t}}
\t}}
\treturn {{}}, false
}}

@(rodata)
enc_entries := []Enc_Entry{{
{body}
}}
'''
    open(OUT, "w", encoding="utf-8").write(src)
    print(f"baked {len(entries)} entries -> {OUT}")


if __name__ == "__main__":
    main()
