bidding_system_unique_header_contexts = {
    ((3, "1C Weak Strong"),),
    ((3, "1C Weak Strong"), (4, "1C Interference"), (6, "Differences with 1D interference")),
    ((3, "1C Weak Strong"), (4, "1C--1D")),
    ((3, "1C Weak Strong"), (4, "1C--1HS")),
    ((3, "1C Weak Strong"), (4, "1C--1N")),
    ((3, "1C Weak Strong"), (4, "1C--1N"), (6, "Interference over 1C--1N")),
    ((3, "1C Weak Strong"), (4, "1C--2C")),
    ((3, "1C Weak Strong"), (4, "1C--2C"), (6, "Interference over 1C--2C")),
    ((3, "1C Weak Strong"), (4, "1C--2D")),
    ((3, "1C Weak Strong"), (4, "1C--2D"), (6, "Interference over 1C--2D")),
    ((3, "1C Weak Strong"), (4, "1C--2H")),
    ((3, "1C Weak Strong"), (4, "1C--2H"), (6, "Interference over 1C--2H")),
    ((3, "1C Weak Strong"), (4, "1C--2S")),
    ((3, "1C Weak Strong"), (4, "1C--2S"), (6, "Interference over 1C--2S")),
    ((3, "1C Weak Strong"), (4, "1C--3N")),
    ((3, "1C Weak Strong"), (4, "1C--4CD")),
    ((3, "1C Weak Strong"), (4, "1C--4HS")),
    ((3, "1C Weak Strong"), (4, "2nd and 4th interfere, Responder Passes")),
    ((3, "1C Weak Strong"), (4, "4th Interferes after Responder Negative")),
    ((3, "1C Weak Strong"), (4, "4th interferes after 2H/2S/2N positive response")),
    (
        (3, "1C Weak Strong"),
        (4, "4th interferes, maybe 2nd, Responder positive"),
        (5, "1 level double by 4th"),
        (6, "Double jump plus interference:"),
    ),
    (
        (3, "1C Weak Strong"),
        (4, "4th interferes, maybe 2nd, Responder positive"),
        (5, "1 level double by 4th"),
        (6, "Jump interference:"),
    ),
    (
        (3, "1C Weak Strong"),
        (4, "4th interferes, maybe 2nd, Responder positive"),
        (5, "1 level double by 4th"),
        (6, "Suit bid where opener can only support responder at 3+ level, e.g:"),
    ),
    (
        (3, "1C Weak Strong"),
        (4, "4th interferes, maybe 2nd, Responder positive"),
        (5, "1 level double by 4th"),
        (6, "Suit bid where opener can support responder at 2 level after interference:"),
    ),
    ((3, "1C Weak Strong"), (4, "4th interferes, maybe 2nd, Responder positive"), (6, "1 level overcall by 4th:")),
    ((3, "1C Weak Strong"), (4, "4th interferes, maybe 2nd, Responder positive"), (6, "1 level takeout by 4th:")),
    (
        (3, "1C Weak Strong"),
        (4, "4th interferes, maybe 2nd, Responder positive"),
        (6, "X by 4th after some 1 level transfer bid, e.g:"),
    ),
    (
        (3, "1C Weak Strong"),
        (4, "4th interferes, maybe 2nd, Responder positive"),
        (6, "X by 4th after some 2 level transfer bid, e.g:"),
    ),
    ((3, "1D Opening"),),
    ((3, "1D Opening"), (4, "1D interference")),
    ((3, "1D Opening"), (4, "1D interference"), (6, "(optional) 1D--(P)--1S--(X) Interference")),
    (
        (3, "1D Opening"),
        (4, "1D interference"),
        (6, "2H interference by 4th, partner shown spades then 2N is Minors Scrambling"),
    ),
    (
        (3, "1D Opening"),
        (4, "1D interference"),
        (6, "2S interference by 4th, partner shown hearts then 2N is Good-Bad"),
    ),
    ((3, "1D Opening"), (4, "1D interference"), (6, "Choice of game 4x cue bids after Thrump double")),
    ((3, "1D Opening"), (4, "1D interference"), (6, "Extra trump redouble after settling in 2HS")),
    ((3, "1D Opening"), (4, "1D interference"), (6, "Opener's cue bid")),
    ((3, "1D Opening"), (4, "1D interference"), (6, "Support doubles and redoubles by opener")),
    ((3, "1D Opening"), (4, "1D--1H")),
    ((3, "1D Opening"), (4, "1D--1H"), (5, "1D--1H--1N")),
    ((3, "1D Opening"), (4, "1D--1H"), (5, "1D--1H--1S")),
    ((3, "1D Opening"), (4, "1D--1H"), (5, "1D--1H--2C")),
    ((3, "1D Opening"), (4, "1D--1H"), (5, "1D--1H--2D")),
    ((3, "1D Opening"), (4, "1D--1H"), (5, "1D--1H--2H")),
    ((3, "1D Opening"), (4, "1D--1H"), (5, "1D--1H--2S")),
    ((3, "1D Opening"), (4, "1D--1N")),
    ((3, "1D Opening"), (4, "1D--1S")),
    ((3, "1D Opening"), (4, "1D--1S--1N")),
    ((3, "1D Opening"), (4, "1D--1S--1N"), (5, "1D--1S--2C")),
    ((3, "1D Opening"), (4, "1D--1S--1N"), (5, "1D--1S--2D")),
    ((3, "1D Opening"), (4, "1D--1S--1N"), (5, "1D--1S--2H")),
    ((3, "1D Opening"), (4, "1D--1S--1N"), (5, "1D--1S--2S")),
    ((3, "1D Opening"), (4, "1D--2C")),
    ((3, "1D Opening"), (4, "1D--2C"), (5, "1D--2C Interference")),
    ((3, "1D Opening"), (4, "1D--2D")),
    ((3, "1D Opening"), (4, "1D--2D"), (5, "1D--2D Interference")),
    ((3, "1H Opening"),),
    ((3, "1H Opening"), (4, "1H interference")),
    ((3, "1H Opening"), (4, "1H interference"), (5, "4th only overcalls:")),
    ((3, "1H Opening"), (4, "1H interference"), (5, "responder passing, 4th hand reopens")),
    ((3, "1H Opening"), (4, "1H--1N")),
    ((3, "1H Opening"), (4, "1H--1S")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--1N")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--2C")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--2D")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--2H")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--2N")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--2S")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--3C")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--3D")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--3H")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--3N/4x")),
    ((3, "1H Opening"), (4, "1H--1S"), (5, "1H--1S--3S")),
    ((3, "1H Opening"), (4, "1H--2C")),
    ((3, "1H Opening"), (4, "1H--2D")),
    ((3, "1H Opening"), (4, "1H--2H")),
    ((3, "1H Opening"), (4, "1H--2H"), (5, "interference by 4th")),
    ((3, "1H Opening"), (4, "1H--2N")),
    ((3, "1H Opening"), (4, "1H--2N"), (5, "2N Invite Plus Interference")),
    ((3, "1H Opening"), (4, "1H--2S")),
    ((3, "1H Opening"), (4, "1H--3CD"), (5, "1H--3C")),
    ((3, "1H Opening"), (4, "1H--3CD"), (5, "1H--3D")),
    ((3, "1H Opening"), (4, "1H--3S")),
    ((3, "1NT Escape"),),
    ((3, "1NT Interference and Lebensohl"), (5, "Better Minor Lebensohl")),
    ((3, "1NT Interference and Lebensohl"), (5, "Over a balanced hand")),
    ((3, "1NT Interference and Lebensohl"), (5, "Reversed Lebensohl RLEB")),
    ((3, "1NT Opening"),),
    ((3, "1NT Opening"), (5, "1N--2C"), (6, "1N--2C--2D")),
    ((3, "1NT Opening"), (5, "1N--2C"), (6, "1N--2C--2H")),
    ((3, "1NT Opening"), (5, "1N--2C"), (6, "1N--2C--2S")),
    ((3, "1NT Opening"), (5, "1N--2D")),
    ((3, "1NT Opening"), (5, "1N--2D"), (6, "Transfer breaks")),
    ((3, "1NT Opening"), (5, "1N--2H")),
    ((3, "1NT Opening"), (5, "1N--2H"), (6, "Transfer breaks")),
    ((3, "1NT Opening"), (5, "1N--2S/2N")),
    ((3, "1NT Opening"), (5, "1N--3C")),
    ((3, "1NT Opening"), (5, "1N--3D")),
    ((3, "1NT Opening"), (5, "1N--3H")),
    ((3, "1NT Opening"), (5, "1N--3S")),
    ((3, "1NT Opening"), (5, "1N--4CD")),
    ((3, "1S Opening"),),
    ((3, "1S Opening"), (4, "1S interference")),
    ((3, "1S Opening"), (4, "1S interference"), (5, "4th only overcalls:")),
    ((3, "1S Opening"), (4, "1S interference"), (5, "responder passing, 4th hand reopens")),
    ((3, "1S Opening"), (4, "1S--1N")),
    ((3, "1S Opening"), (4, "1S--2C")),
    ((3, "1S Opening"), (4, "1S--2D")),
    ((3, "1S Opening"), (4, "1S--2H")),
    ((3, "1S Opening"), (4, "1S--2N")),
    ((3, "1S Opening"), (4, "1S--2S")),
    ((3, "1S Opening"), (4, "1S--2S"), (5, "interference by 4th")),
    ((3, "1S Opening"), (4, "1S--3CD"), (5, "1S--3C")),
    ((3, "1S Opening"), (4, "1S--3CD"), (5, "1S--3D")),
    ((3, "1S Opening"), (4, "1S--3CD"), (5, "1S--3H")),
    ((3, "1S Opening"), (4, "1S--3N")),
    ((3, "2C Intermediate Opening"),),
    ((3, "2C Intermediate Opening"), (4, "2C Interference")),
    ((3, "2C Intermediate Opening"), (5, "2C--2D--3C+")),
    ((3, "2C Intermediate Opening"), (5, "2D enquiry")),
    ((3, "2C Intermediate Opening"), (5, "2D enquiry"), (6, "2C--2D--2H")),
    ((3, "2C Intermediate Opening"), (5, "2D enquiry"), (6, "2C--2D--2N")),
    ((3, "2C Intermediate Opening"), (5, "2D enquiry"), (6, "2C--2D--2S")),
    ((3, "2D Intermediate Opening"),),
    ((3, "2D Intermediate Opening"), (4, "2D Intermediate Interference")),
    ((3, "2HS Weak Openings"), (4, "2HS interference")),
    ((3, "2HS Weak Openings"), (5, "Responding"), (6, "2H Opening Responses")),
    ((3, "2HS Weak Openings"), (5, "Responding"), (6, "2S Opening Responses")),
    ((3, "2HS Weak Openings"), (5, "Responding"), (6, "NV 1st/2nd 5 or 6 card Extension")),
    ((3, "2NT Opening"),),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N interference")),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N--3C")),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N--3D")),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N--3H")),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N--3S")),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N--4C")),
    ((3, "2NT Opening"), (4, "Responding to 2N"), (6, "2N--4DH")),
    ((3, "3CD Openings"),),
    ((3, "3HS Openings"),),
    ((3, "3N Opening"),),
    ((3, "4CD Openings"),),
    ((3, "4H 4S 5C 5D Openings"),),
    ((3, "4N Opening"),),
    ((3, "Competitive Auctions"), (4, "2N Artificial Scrambling")),
    ((3, "Competitive Auctions"), (4, "4N is it a Stronger Raise or Unusual in Competition")),
    ((3, "Competitive Auctions"), (4, "4th balancing of 1x openings"), (6, "responding to 4th balancing takeout X")),
    ((3, "Competitive Auctions"), (4, "Advancer's 2C Relay")),
    ((3, "Competitive Auctions"), (4, "Opener's Good-Bad 2N Rebid After Major NF")),
    ((3, "Competitive Auctions"), (4, "Opener's Good-Bad 2N Rebid in Competition")),
    ((3, "Competitive Auctions"), (4, "Opener's Renegative Double for Both Majors")),
    ((3, "Competitive Auctions"), (4, "Opener's Second Round Double - After Partner's 2 Level WJS")),
    (
        (3, "Competitive Auctions"),
        (4, "We Open with Fit and Slam Potential then 4th Hand High Level Interference"),
        (6, "3 level rebid available"),
    ),
    (
        (3, "Competitive Auctions"),
        (4, "We Open with Fit and Slam Potential then 4th Hand High Level Interference"),
        (6, "3N bid available"),
    ),
    (
        (3, "Competitive Auctions"),
        (4, "We Open with Fit and Slam Potential then 4th Hand High Level Interference"),
        (6, "No 3N bid available"),
    ),
    ((3, "Doubles"), (4, "2N support raise then we Double")),
    ((3, "Doubles"), (4, "Extra Length 2 Level Double of Cuebid by Opener - Partner not bid")),
    ((3, "Doubles"), (4, "Extra trump redouble - we stop 2HS they takeout X")),
    ((3, "Doubles"), (4, "Handling doubles of our stopper ask of their suit")),
    ((3, "Doubles"), (4, "Relay Lebensohl Doubles")),
    ((3, "Doubles"), (4, "Single Raise they Compete We Double")),
    ((3, "Doubles"), (4, "Stolen Double by advancer - Opponents' HCR double")),
    ((3, "Opponents open 1C Natural (Quasi)"), (5, "(1C)--(Any) Sandwich Position")),
    ((3, "Opponents open 1C Natural (Quasi)"), (5, "4th Balancing 1C")),
    ((3, "Opponents open 1C Natural (Quasi)"), (6, "(1C)--Overcall")),
    ((3, "Opponents open 1C Natural (Quasi)"), (6, "(1C)--X")),
    ((3, "Opponents open 1D"), (5, "(1D)--(Any) Sandwich Position")),
    ((3, "Opponents open 1D"), (5, "4th Balancing 1D")),
    ((3, "Opponents open 1D"), (6, "(1D)--Overcall")),
    ((3, "Opponents open 1D"), (6, "(1D)--X")),
    ((3, "Opponents open 1H"), (5, "4th Balancing 1H")),
    ((3, "Opponents open 1H"), (6, "(1H)--(Any) Sandwich Position")),
    ((3, "Opponents open 1H"), (6, "(1H)--Overcall")),
    ((3, "Opponents open 1H"), (6, "(1H)--X")),
    ((3, "Opponents open 1NT"),),
    ((3, "Opponents open 1NT"), (4, "Strong NT Defence")),
    ((3, "Opponents open 1S"), (5, "4th Balancing 1S")),
    ((3, "Opponents open 1S"), (6, "(1S)--(Any) Sandwich Position")),
    ((3, "Opponents open 1S"), (6, "(1S)--Overcall")),
    ((3, "Opponents open 1S"), (6, "(1S)--X")),
    ((3, "Opponents open 2D or 2H Flannery"),),
    ((3, "Opponents open 2D or 2H both Majors"),),
    ((3, "Opponents open 2N Minors"),),
    ((3, "Opponents open 3CDHS"),),
    ((3, "Opponents open 3N"),),
    ((3, "Opponents open 4CD SAT/Namyats"),),
    ((3, "Opponents open 4CD preempt"),),
    ((3, "Opponents open 4HS"),),
    ((3, "Opponents open 5CD"),),
    ((3, "Opponents open Intermediate 2C"),),
    ((3, "Opponents open Multi 2C"),),
    ((3, "Opponents open Multi 2D"),),
    ((3, "Opponents open Strong 1C"),),
    ((3, "Opponents open Strong 2C"),),
    ((3, "Opponents open Weak 2D 2H 2S"),),
    ((3, "Overcalls of our NT"), (5, "NT Interference")),
    ((3, "Slam Bidding"), (4, "Cue Bids"), (5, "Opponents Double Our Cue Bid")),
    ((3, "Slam Bidding"), (4, "Cue Bids"), (5, "Serious 3N Replaces Immediate Cue Bid")),
    ((3, "Slam Bidding"), (4, "Double Fit RKB")),
    ((3, "Slam Bidding"), (4, "EKB Voidwood"), (5, "EKB King Request when no 5N available")),
    ((3, "Slam Bidding"), (4, "EKB Voidwood"), (5, "EKB Responses")),
    ((3, "Slam Bidding"), (4, "Free 5x Major Raise")),
    ((3, "Slam Bidding"), (4, "Lackwood")),
    ((3, "Slam Bidding"), (4, "RKB 4N"), (5, "King Ask")),
    ((3, "Slam Bidding"), (4, "RKB 4N"), (5, "When can sign off at 5 level")),
    ((3, "Slam Bidding"), (4, "RKB 4N"), (5, "When forced to slam")),
    ((3, "Slam Bidding"), (4, "RKB 4N"), (5, "void response continuation with no room below slam")),
    ((3, "Uncontested Openings Summary"),),
}

squad_system_unique_header_contexts = {
    ((3, "1C Interference"),),
    ((3, "1C Interference"), (4, "4th interference")),
    ((3, "1C Opening"),),
    ((3, "1C Opening"), (4, "1C--1D")),
    ((3, "1C Opening"), (4, "1C--1H")),
    ((3, "1C Opening"), (4, "1C--1N")),
    ((3, "1C Opening"), (4, "1C--1S")),
    ((3, "1D Interference"),),
    ((3, "1D Interference"), (4, "4th interference")),
    ((3, "1D Opening"),),
    ((3, "1D Opening"), (4, "1D--1H")),
    ((3, "1D Opening"), (4, "1D--1N")),
    ((3, "1D Opening"), (4, "1D--1S")),
    ((3, "1H Interference"),),
    ((3, "1H Interference"), (4, "4th interference")),
    ((3, "1H Opening"),),
    ((3, "1H Opening"), (4, "1H--1N")),
    ((3, "1H Opening"), (4, "1H--1S")),
    ((3, "1H Opening"), (4, "1H--2C")),
    ((3, "1H Opening"), (4, "1H--2D")),
    ((3, "1N Interference"),),
    ((3, "1NT Opening"),),
    ((3, "1NT Opening"), (4, "1N--2D/2H transfers")),
    ((3, "1S Interference"),),
    ((3, "1S Interference"), (4, "4th interference")),
    ((3, "1S Opening"),),
    ((3, "1S Opening"), (4, "1S--1N")),
    ((3, "1S Opening"), (4, "1S--2C")),
    ((3, "1S Opening"), (4, "1S--2D")),
    ((3, "2C Interference"),),
    ((3, "2C Opening"),),
    ((3, "2C Opening"), (4, "2C--2D")),
    ((3, "2D Interference"),),
    ((3, "2D Opening"),),
    ((3, "2D Opening"), (4, "Weak Two Ask")),
    ((3, "2H Interference"),),
    ((3, "2H Opening"),),
    ((3, "2N Interference"),),
    ((3, "2N Opening"),),
    ((3, "2S Interference"),),
    ((3, "2S Opening"),),
    ((3, "3CDHS Interference"),),
    ((3, "3CDHS Opening"),),
    ((3, "3N Interference"),),
    ((3, "3N Opening"),),
    ((3, "4CDHS Opening"),),
    ((3, "Opening Bids Summary"),),
    ((3, "Opponents Open 1C"), (4, "(1C)--(Any) Sandwich Position")),
    ((3, "Opponents Open 1C"), (4, "(1C)--Overcall")),
    ((3, "Opponents Open 1C"), (4, "(1C)--X")),
    ((3, "Opponents Open 1C"), (4, "4th Balancing 1C")),
    ((3, "Opponents Open 1D"), (4, "(1D)--(Any) Sandwich Position")),
    ((3, "Opponents Open 1D"), (4, "(1D)--Overcall")),
    ((3, "Opponents Open 1D"), (4, "(1D)--X")),
    ((3, "Opponents Open 1D"), (4, "4th Balancing 1D")),
    ((3, "Opponents Open 1H"), (4, "(1H)--(Any) Sandwich Position")),
    ((3, "Opponents Open 1H"), (4, "(1H)--Overcall")),
    ((3, "Opponents Open 1H"), (4, "(1H)--X")),
    ((3, "Opponents Open 1H"), (4, "4th Balancing 1H")),
    ((3, "Opponents Open 1N"),),
    ((3, "Opponents Open 1S"), (4, "(1S)--(Any) Sandwich Position")),
    ((3, "Opponents Open 1S"), (4, "(1S)--Overcall")),
    ((3, "Opponents Open 1S"), (4, "(1S)--X")),
    ((3, "Opponents Open 1S"), (4, "4th Balancing 1S")),
    ((3, "Opponents Open Multi 2D"),),
    ((3, "Opponents Open Weak Four"),),
    ((3, "Opponents Open Weak Three"),),
    ((3, "Opponents Open Weak Two"),),
    ((3, "Opponents Strong 1C"),),
}
